# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2

registries:
  maven-central:
    type: maven-repository
    url: https://repo.maven.apache.org/maven2
  maven-github:
    type: maven-repository
    url: https://maven.pkg.github.com/derBobby
    username: derBobby
    token: ${{secrets.REPO_PACKAGES_PAT}}

updates:

  - package-ecosystem: "github-actions" # See documentation for possible values
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(actions deps)"  # Ensures changes trigger a release
      include: "scope"

  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
    registries:
      - maven-github
      - maven-central # Default Maven registry
    commit-message:
      prefix: "chore(mvn deps)"  # Ensures changes trigger a release
      include: "scope"
    ignore:
      - dependency-name: "org.springframework.boot:*"
        update-types: [ "version-update:semver-major" ]

  - package-ecosystem: "npm"
    directory: "/"  # Change if package.json is in a subdirectory
    schedule:
      interval: "daily"
    commit-message:
      prefix: "chore(npm deps)"  # Ensures changes trigger a release
      include: "scope"